### ISSUE TITLE
Is it normal that CPU usage is at 100% while GPU is underutilize?

### ISSUE THREAD

**Issue by jackkwok** [killthekitten/kaggle-ds-bowl-2018-baseline#10]
When training my own dataset, I notice the CPU is always at 100% while the GPU spent 90%+ of the time at 0% with occasional spikes to 99%.  CPU appears to be the bottleneck.  

Is it normal that CPU usage is at 100% while GPU is underutilize?

I tried the set use_multiprocessing = True (fit_generator) but program crashed.  What do I need to change to allow for multiprocessing?  Hoping that will speed up training.

**Comment by killthekitten** [comment]
Sorry for the late reply. It already uses multithreading to load the data in the background. Have you done any changes to the original dataset class? It might be some issue around that.

**Comment by killthekitten** [comment]
Also, what hardware do you run it on?
