### ISSUE TITLE
Evaluation Exception: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by John1231983** [killthekitten/kaggle-ds-bowl-2018-baseline#2]
Hello, I am using your repo and my custom setting. I got 0.34LB for SGD. I changed to Adam and encoded submission again. However, when I submit to the system, I got the error:

>Evaluation Exception: Index was outside the bounds of the array.

I think your code has some bug in somewhere in the inference that output size does not match with original size or other reasons.

This is my submission file
[submission.csv.zip](https://github.com/killthekitten/kaggle-ds-bowl-2018-baseline/files/1777307/submission.csv.zip)

**Comment by killthekitten** [comment]
@John1231983 I've spotted this one for myself too.

Let's check: you've achieved 0.34LB using this repo and it worked properly?

**Comment by John1231983** [comment]
Sorry. I have check again. It above 0.32 after 50 epcho. I think it may be better if I run more but your code is too slow due to you turn off the multiple processing flag

**Comment by John1231983** [comment]
I think I know the issue. It may be you did not take argmax of a pixel if they maintain two predictions. It is known as remove mask function in the original mask rcnn implementation. 

You can refer the code function `numpy2encoding_no_overlap2` in the https://github.com/YanWang2014/Mask_RCNN/blob/master/Spot-Nuclei2/val_test2.py

**Comment by killthekitten** [comment]
@John1231983 it should be something else, because I handle that case here https://github.com/killthekitten/kaggle-ds-bowl-2018-baseline/blob/master/inference.py#L49. 

Could you change the code to @YanWang2014's and check in your local setup? Appreciate it.

**Comment by John1231983** [comment]
Hi. I have change it and it worked. So, I guess that your problem with the above reason
Update: For now, I got 0.40 using your code and my config with Adam Optimization, 50 epcho

**Comment by killthekitten** [comment]
@John1231983 Could you share the fix in a separate PR? Thanks!

**Comment by John1231983** [comment]
Sure. I will update it

**Comment by John1231983** [comment]
Sorry. I don't know why I cannot make the separate PR. Could you check the diff in this one and modify your code https://github.com/John1231983/kaggle-ds-bowl-2018-baseline

**Comment by killthekitten** [comment]
@John1231983 thanks, I'll handle it from here :+1:
