### ISSUE TITLE
Discussion about speed up loading dataset

### ISSUE THREAD

**Issue by John1231983** [killthekitten/kaggle-ds-bowl-2018-baseline#3]
This is not issue because the code run correctly. I open it to discuss about loading dataset function that often takes a lot of time.

In the `load_image_gt`, we call the `load_image` and `load_mask` every iterations. That often takes take to decode jgp images. Hence, I suggest use other ways to speed up it:
1. Tfrecord file if it is possible (best)
2. Store in an array (store in RAM) until the program finish

Thanks

**Comment by killthekitten** [comment]
We should add both options. I'd personally go with RAM-only, but that could break on others' machines.

**Comment by John1231983** [comment]
Have you complete with storing in Ram? I would like to test it. I found that almost time consuming is from load image.. FYI, you can also try newest tensorflow that may manager memory better( I heard that:)

**Comment by killthekitten** [comment]
@John1231983 haven't touched that yet, working on augmentation right now.

**Comment by killthekitten** [comment]
Just for the record: storing masks in a numpy format worked well for me. I've added a script to generate the mosaics and their respective numpy files. 

Brief description can be found here: https://www.kaggle.com/c/data-science-bowl-2018/discussion/51487

Some additional discussion is going on in #5.

**Comment by John1231983** [comment]
For anyone interested, this is my modify function based on the suggestion of @killthekitten to work with his output. We have to rewrite the dataset class as
```
class BowlDataset(Dataset):  
       def load_bowl(self, base_path):
        """Generate the requested number of synthetic images.
        count: number of images to generate.
        height, width: the size of the generated images.
        """
        self.add_class("bowl", 1, "nuclei")
        
        masks = dict()
        # id_extractor = re.compile(base_path + "\/(?P<image_id>.*)\/masks\/(?P<mask_id>.*)\.png")
        for mask_path in glob(os.path.join(base_path, "*.npy")):
            image_id=os.path.splitext(os.path.basename(mask_path))[0]
            image_path = os.path.join(base_path, image_id + ".png")
            if image_path in masks:
                masks[image_path].append(image_path)
            else:
                masks[image_path] = mask_path
        for i, (image_path, mask_paths) in enumerate(masks.items()):
            self.add_image("bowl", image_id=i, path=image_path, mask_paths=mask_paths)

    def load_image(self, image_id):
        info = self.image_info[image_id]
        return cv2.imread(info["path"])

    def load_mask(self, image_id):
        info = self.image_info[image_id]
        mask = np.load(info["mask_paths"])
        class_ids = np.ones(mask.shape[-1])
        return mask, class_ids.astype(np.int32)

```

@killthekitten : Could you check the function `load_bowl`? Is it fine? It worked for me
I have run it and I did not see any improvement (take 579ms/step). My RAM is 32GB. I just changed the dataset class. Keep the function `load_image_gt`, (just add small function to cropping)
```

def load_image_gt(dataset, config, image_id, augment=False,
                  use_mini_mask=False):
     # Load image and mask
    image = dataset.load_image(image_id)
    mask, class_ids = dataset.load_mask(image_id)
    shape = image.shape
    # Cropping image output of 512x512 image and it mask
   ...
```

**Comment by killthekitten** [comment]
The code seems good. How much time did a step take before that for you? I would estimate it to be close to a second on average. 

I think the rest is the network. You could try profiling the code to understand how much time is actually spent on each part.

**Comment by John1231983** [comment]
If I use the way to load png and its masks (as the case 1), it also takes around this time (500ms/step or less) if I remember. But the benefit is that the saving memory in the disk is much smaller. I am using number of image is 1
```
GPU_COUNT = 1
IMAGES_PER_GPU = 1
```
It takes less than 8GB
```
             total        used        free      shared  buff/cache   available
Mem:          32107        8301        4466         623       19340       22635
Swap:          2010        1550         460

```
