### ISSUE TITLE
Training for two classes

### ISSUE THREAD

**Issue by fastlater** [killthekitten/kaggle-ds-bowl-2018-baseline#4]
Where did you set that the class color will be white [255,255,255]? In case I would like to detect 2 classes, how do I define the new class name and color?

I have been reading some of the scripts looking for the code lines where you define the mask  color but I still cannot find it. load_mask function?

I will thanks a lot if someone point me out in the right direction.

**Comment by killthekitten** [comment]
Hey there! The easiest way to make sense of it is to interrogate this notebook: https://github.com/matterport/Mask_RCNN/blob/master/train_shapes.ipynb

Hope this helps :) Any ideas how to use a multiclass segmentation for the Bowl problem?

**Comment by killthekitten** [comment]
You're interested in this array in the end of `load_masks` function:
```
class_ids = np.array([self.class_names.index(s[0]) for s in shapes])
```

Each element in this array contains a class id and this element's index is equal to the layer index in the mask. The pixels in the mask are still a bunch of zeros and ones, no class info is encoded in the mask itself.

**Comment by fastlater** [comment]
@killthekitten  Thank you for your replies. I will try and come back here if I make it.
