### ISSUE TITLE
How to merge sub-masks and merge masks in the edge?

### ISSUE THREAD

**Issue by John1231983** [killthekitten/kaggle-ds-bowl-2018-baseline#5]
Hello, thanks for sharing the code merge and combine masks and images together. I have a question using it. I load an image and masks from training dataset. I want to crop the image into 4 sub-images and masks. After that, I used your code to combine and merge layers in the edge. However, it gives me an unexpected result that deleted masks in the edges. thus I cannot recover the original masks(before cropping). This is my output using the below code of `id=c901794d1a421d52e5734500c0a2a8ca84651fb93b19cec2f411855e70cae339`. In additions, what is happen if these sub-images overlapping? For example, `image_crop1=image[:512,:512,:], image_crop3=image[500:,:500,:]`

![mask](https://user-images.githubusercontent.com/24875971/37223061-af34e91c-2412-11e8-80c1-78b082037a1f.png)

```
import numpy as np
from bowl_dataset import BowlDataset
from rebuild_mosaics import *
#=============Pre-paring dataset=================
dataset_train = BowlDataset()
dataset_train.load_bowl('./merge_test')
dataset_train.prepare()
#=============Load original image and masks======
image=dataset_train.load_image(0)
masks, class_ids = dataset_train.load_mask(0)
#=============Crop image into some sub-images====
image_crop1=image[:512,:512,:]
masks_crop1=masks[:512,:512,:]
zeros_mask1 = masks_crop1.sum((0, 1)) == 0
masks_crop1 = masks_crop1[..., ~zeros_mask1]

image_crop2=image[:512,512:,:]
masks_crop2=masks[:512,512:,:]
zeros_mask2 = masks_crop2.sum((0, 1)) == 0
masks_crop2 = masks_crop2[..., ~zeros_mask2]

image_crop3=image[512:,:512,:]
masks_crop3=masks[512:,:512,:]
zeros_mask3 = masks_crop3.sum((0, 1)) == 0
masks_crop3 = masks_crop3[..., ~zeros_mask3]

image_crop4=image[512:,512:,:]
masks_crop4=masks[512:,512:,:]
zeros_mask4 = masks_crop4.sum((0, 1)) == 0
masks_crop4 = masks_crop4[..., ~zeros_mask4]
#==============Merge sub-masks into big masks=======
channels_count = masks_crop1.shape[2]+masks_crop2.shape[2]+masks_crop3.shape[2]+masks_crop4.shape[2]
h,w,_=image.shape
masks_merge = np.zeros((h,w, channels_count), dtype=np.bool)
current_c=0
for i in range (masks_crop1.shape[2]):
    masks_merge[:512,:512,current_c]=masks_crop1[:,:,i]
    current_c=current_c+1

for i in range (masks_crop2.shape[2]):
    masks_merge[:512,512:,current_c]=masks_crop2[:,:,i]
    current_c=current_c+1

for i in range (masks_crop3.shape[2]):
    masks_merge[512:,:512,current_c]=masks_crop3[:,:,i]
    current_c=current_c+1

for i in range (masks_crop4.shape[2]):
    masks_merge[512:,512:,current_c]=masks_crop4[:,:,i]
    current_c=current_c+1
#==========Merge the masks on the edges================
masks_merge, delete_counts=merge_layers_on_edges(masks)

```

**Comment by killthekitten** [comment]
Please, pay attention to the comments in the code. Because of the specific sort of Emil's data, I glue the images like this:
```
2 3
0 1
```

While your code most likely feeds the masks in a more intuitive way (which is not what I intended):
```
0 1 
2 3
```

Sorry for the mess, just swap the first two crops with the last two.

**Comment by John1231983** [comment]
Thanks. I solved my problem by rewriting the new code :(. The new problem come `Memory error` in `load_masks` at the line `stack` during training, i.e. image id `30, 17...`. I have rewritten your code by save the image and its mask to png file that follows the rule of the challenge, i.e. 
```
mosaics
-1
--images
---1.png
--masks
---1.png
---2.png
---3.png
```
For the format, I can use same database loading function (your saving npy too much memory in disk). However, I got the above meomory error (the image id 30 has more than 600 masks image)
```

File "/home/john/kaggle-ds-bowl-2018-baseline/model.py", line 1880, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/john/kaggle-ds-bowl-2018-baseline/model.py", line 1411, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/home/john/kaggle-ds-bowl-2018-baseline/bowl_dataset.py", line 72, in load_mask
    masks = np.where(masks > 128, 1, 0)
```
Do you have same problem when using mosaics?

**Comment by killthekitten** [comment]
Oh, so turns out you've used an old version of code. The most recent one doesn't use `stack` and is more efficient. It has also fixed the file size issue and some more.

As for the training process, I use crops to train with mosaics, so no memory issues here.

**Comment by John1231983** [comment]
Sorry. The line is `where(masks>128,1,0)`, not `stack` line. I am using the code in the
[line 61 of bowl_dataset.py](https://github.com/killthekitten/kaggle-ds-bowl-2018-baseline/blob/master/bowl_dataset.py#L61)

For training, how do you solve it? Because, first I have to load the image and its masks, then crop the image and image with desired size (such as 512x512). The above error comes from the first step

**Comment by killthekitten** [comment]
You didn't show the actual error, so hard to guess what was it judging by only the backtrace.

**Comment by John1231983** [comment]
This is my code. In the `load_image_gt` of model.py, I used
```
  # Load image and mask
    image = dataset.load_image(image_id)
    mask, class_ids = dataset.load_mask(image_id)
```
Where load_mask is
 ```
def load_mask(self, image_id):
        info = self.image_info[image_id]
        mask_paths = info["mask_paths"]
        count = len(mask_paths)      
        masks = [skimage.io.imread(path) for path in mask_paths]
        masks = np.stack(masks, axis=-1)
        masks = np.where(masks > 128, 1, 0)  
        class_ids = np.ones(count)
        return masks, class_ids.astype(np.int32)
```
And the above error comes. It only happened with images have many masks such as id 30, 17. Otherwise, it worked well.

**Comment by killthekitten** [comment]
Sorry, I still don't get what the actual error was, I mean, could you provide a full error message?

**Comment by John1231983** [comment]
The full error is
```
ERROR:root:Error processing image {'id': 61, 'path': 'stage1_train/mosaics/17/images/17.png', 'source': 'bowl', 'mask_paths': ['stage1_train/mosaics/17/masks/masks_589.png', 'stage1_train/mosaics/17/masks/masks_52.png', 'stage1_train/mosaics/17/masks/masks_208.png', 'stage1_train/mosaics/17/masks/masks_480.png', 'stage1_train/mosaics/17/masks/masks_511.png', 'stage1_train/mosaics/17/masks/masks_588.png', 'stage1_train/mosaics/17/masks/masks_373.png', 'stage1_train/mosaics/17/masks/masks_746.png', 'stage1_train/mosaics/17/masks/masks_485.png', 'stage1_train/mosaics/17/masks/masks_103.png', 'stage1_train/mosaics/17/masks/masks_58.png', 'stage1_train/mosaics/17/masks/masks_307.png', 'stage1_train/mosaics/17/masks/masks_823.png', 'stage1_train/mosaics/17/masks/masks_560.png', 'stage1_train/mosaics/17/masks/masks_22.png', 'stage1_train/mosaics/17/masks/masks_704.png', 'stage1_train/mosaics/17/masks/masks_178.png', 'stage1_train/mosaics/17/masks/masks_82.png', 'stage1_train/mosaics/17/masks/masks_....

File "/home/john/kaggle-ds-bowl-2018-baseline/model.py", line 1880, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/john/kaggle-ds-bowl-2018-baseline/model.py", line 1411, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/home/john/kaggle-ds-bowl-2018-baseline/bowl_dataset.py", line 72, in load_mask
    masks = np.where(masks > 128, 1, 0)
```

**Comment by killthekitten** [comment]
So yea, I've fixed this by loading masks from .npy files and reducing the queue size to 50. This way the training process uses about 15 gigs of ram at peak.

**Comment by John1231983** [comment]
Could you show me your load mask function? Actually, I changed to save the image to file because .npy takes a lot of memory storing. Thanks for giving me the information that it can be used to speed up loading.

**Comment by killthekitten** [comment]
It couldn't be more simple:

```python
    def load_image(self, image_id):
        info = self.image_info[image_id]

        return cv2.imread(info["path"])

    def load_mask(self, image_id):
        info = self.image_info[image_id]
        mask = np.load(info["mask_path"])
        class_ids = np.ones(mask.shape[-1])
        
        return mask, class_ids.astype(np.int32)
```

**Comment by John1231983** [comment]
Thanks so much. To use your code, which kind of data structure should we use? The first way is following by challenge rule, and the second way is your output using the converted code. To use the second way, I guess we have to rewrite the `load_bowl` function

- The first way
```
mosaics
└───1
│   │  
│   └───images
│   │   │   1.png
│   │  
│   └───masks
│       │   1.npy
│       
└───2
│   │  
│   └───images
│   │   │   2.png
│   │  
│   └───masks
│       │   2.npy
```
- The second way
```
mosaics
   │  
   └───1.png
   └───1.npy
   │  
   └───2.png
   └───2.npy

```
I also not clear that how you can speed up the loading dataset because the `load_image_gt` call the load_mask very iterations, so if I use your current code in this repo, I think we cannot achieve  15 gigs of ram at peak.

**Comment by killthekitten** [comment]
The second way is how you should use it, that's simply the output of `rebuild_mosaics.py`.

This line defines the number of threads that call `load_image_gt` simultaneously, just tune it to fit in the memory:
https://github.com/killthekitten/kaggle-ds-bowl-2018-baseline/blob/master/model.py#L2239

And of course I modified `load_image_gt` to cut random patches.

**Comment by killthekitten** [comment]
I hope this helped! Closing for now.
