### ISSUE TITLE
Scheme to reduce the memory of npy saving files 

### ISSUE THREAD

**Issue by John1231983** [killthekitten/kaggle-ds-bowl-2018-baseline#8]
Hi, your current implementation for saving npy file looks fine but the memory store is too big due to using 3D array. (400mb/file). So we can reduce it by two steps:
1. Create 2D array. For each mask, it will have 1 integer value from 0 to number of mask. Using this scheme, we not only save all masks in a 2D matrix and make memory storing smaller, but also can seperate each mask based on the integer number.
2. Modify the load mask to convert from 2D to 3D matrix by a loop from 0 to number of mask
 Hope it can help saving store npy file

**Comment by killthekitten** [comment]
Yea, this is a good solution. I'd be glad if you'd implement this and provide a separate dataset to decode this format.
